version: "3.8"
services:
  web:
    build: .
    volumes:
      - ./site:/var/www/html
    ports:
      - 80:80

  db:
    image: "mysql:5.7"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: docker_database
    ports:
      - 3306:3306
